server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bruno
    password: bruno
    url: jdbc:postgresql://localhost:5432/backend
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    root: error
    org.springframework: error